import os

ENV_TOKEN = 'SERVOSKULL_TOKEN'
ENV_PREFIX = 'SERVOSKULL_CMD_PREFIX'
ENV_USE_AVCONV = 'SERVOSKULL_AVCONV'

DISCORD_TOKEN = os.getenv(ENV_TOKEN, None)
CMD_PREFIX = os.getenv(ENV_PREFIX, '!')
USE_AVCONV = True if os.getenv(ENV_USE_AVCONV) else False
